### ISSUE TITLE
v5.0 some other plugins conflict

### ISSUE THREAD

**Issue by brjuseg** [galaipa/SuperBuildBattle#12]
Hello, it`s me again :P
1. Some plugins stops working.
2. Right after start of the first game and lasts until server restart
3. spigot 1.8.6 SBB 5.0
4. logs clean except for that lines:
[00:24:00] [Server thread/WARN]: [WorldBorder] Border-checking task was not running! Something on your server apparently killed it. It will now be restarted.
[00:24:00] [Server thread/INFO]: [WorldBorder] [CONFIG] Border-checking timed task stopped.

This bug needs some additional explainig. So far i`ve found two conflicting plugins. One is WorldBorder, which leaves warnings in log. Another one is "infernal mobs". It provides items, which buffs you with effects every 10 seconds. That effects stops refreshing after SBB games starts and remains broken untill server restart. Seems like "timed tasks" not working.

P.S.  Please, do new version at a supersonic speed, still can`t use plugin in it`s current state.

**Comment by galaipa** [comment]
I think I have fixed this. Please check if it works :smile: 
http://www.mediafire.com/download/azpp6gf6boyq9w2/SuperBuildBattle.jar

**Comment by brjuseg** [comment]
We are almost there. I`ve updated my server to 1.8.7 core, no armor bug. Other plugins function ok thx to your fix, but now game not starting. It stuck at 10 10 9 9 10 10 10 10. It spams double "10 seconds before the game" messages and goes like that forever.

**Comment by galaipa** [comment]
Very strange, not happening in tests . Have you tryed it more than once?

**Comment by brjuseg** [comment]
yeah, like ten times, with clean server restarts...

**Comment by brjuseg** [comment]
Addition: when i join queue and do /bbadmin and force start, then timer can go even up to 3 and then change to 10 and stuck again.

**Comment by brjuseg** [comment]
Tried again tomorrow with clean server (no plugins at all). Same story, Timer ticks at 10-9 seconds.
My specs are: spigot 1.8.7  java 8 v45 (x64). Idk what info can help...

**Comment by galaipa** [comment]
I think everything is fixed. I will soon upload a new release

**Comment by brjuseg** [comment]
Ok, cause i tried 5.5 and i still have issues with other plugin`s tasks stopped and players loose armor after exit. And i have 1.8.7 spigot now (
